<?php
	$action = $this->getAction(); 
	print $action; // Debug using
?>
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<link rel="stylesheet" type="text/css" href="/css/style.css" media="all">
	<title><?php echo (isset($this->page_title) ? $this->page_title:'Welcome'); ?></title>
</head>
<body>
	<nav class="navbar">
		<ul>
			<li><a href="/home/index" <?php echo ($action == 'home/index'?'class=active':''); ?>>Home</a></li>
			<li><a href="/home/aboutUs" <?php echo ($action == 'home/aboutUs'?'class=active':''); ?>>AboutUs</a></li>
		</ul>
</nav>
