<?php include VIEW.'header.phtml';?>
<h1>User List</h1>

<?php
	if (array_key_exists('users', $this->view_data)) {
		$table = '<table border=1>';
	 	foreach ($this->view_data['users'] as $user_data) 
	 	{
	 		$user_info = explode(',',$user_data);
	 		$table .='<tr>';
	 		foreach ($user_info as $item) 
	 		{
	 			$table .='<td>' . $item . '</td>';
	 		}
	 		$table .='</tr>';
	 	}
	 	$table .='</table>';
	 	echo $table;
	 } 
 ?>

<?php include VIEW.'footer.phtml';?>